### ISSUE TITLE
Wybór płatności nie pojawia się w realizacji zamówienia

### ISSUE THREAD

**Issue by dudekk** [dotpay/PrestaShop-1.7.x#1]
Posiadam świeżą instalację Presty 1.7, zainstalowałem moduł dotpay dla 1.7 w wersji 1.0.1.

Podobnie jak ta osoba tutaj: http://prestashopforum.pl/index.php?topic=15571.0
wybór płatności nie pojawia się w realizacji zamówienia, jest tylko "czek" i "przelew bankowy".

Opcje lokalizacja-płatności itd są ok, wszędzie jest zaznaczony Dotpay.

Czy można jakoś zaradzić temu problemowi? Jeśli będą potrzebne dodatkowe informacje to wyślę.

**Comment by wpawel** [comment]
proszę wysłać szczegóły sklepu (adres, id konta Dotpay) na adres: tech@dotpay.pl

**Comment by dudekk** [comment]
W międzyczasie postawiłem sklep na nowo i na nowej instalacji moduł pokazuje się w realizacji zamówienia, właśnie zrobiłem testowe zamówienie i wszystko przeszło ok, informacja zwrotna wróciła do sklepu.

Są dwie rzeczy kosmetyczne do poprawy:
- po instalacji modułu na czystej wersji pokazuje się błąd, że moduł nie został prawidłowo zainstalowany, jednak instaluje się poprawnie
- link do obrazka jest błędny, sklep mam pod URI /sklep i w adresie obrazka nie jest prefix /sklep brany pod uwagę (/modules/dotpay/views/img/dotpay_logo_big.png zamiast /sklep/modules/dotpay/views/img/dotpay_logo_big.png)
![image](https://cloud.githubusercontent.com/assets/5006623/24508310/51a1a114-1563-11e7-9a98-4c078c4faff1.png)

**Comment by tbajorek** [comment]
1) Czy podczas instalacji modułu pojawiły się jakieś logi z błędami w sklepie albo na serwerze www? Mogłyby one pomóc zdiagnozować, dlaczego pojawił się Panu komunikat, że moduł nie został prawidłowo zainstalowany.
2) Korzysta Pan z opcji multistore?

**Comment by tbajorek** [comment]
Proszę sprawdzić, czy problem 2. został rozwiązany w najnowszej aktualizacji.

**Comment by dudekk** [comment]
Aktualnie nie mogę sprawdzić czy problem drugi został rozwiązany - gdy będę testował 1.7 dalej na tamtym sklepie to sprawdzę.

Przy instalacji modułu występuje błąd "Server responded with 500 code." i moduł w ogóle się nie instaluje, a w logach serwera http:

```
2017/04/24 14:27:08 [error] 19575#19575: *156 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Dotpay\Exception\BadParameter\IdException in /www/modules/dotpay/sdk/Dotpay/Model/Configuration.php:695
Stack trace:
#0 /www/modules/dotpay/classes/Dotpay/Model/Configuration.php(108): Dotpay\Model\Configuration->setId(false)
#1 [internal function]: Prestashop\Dotpay\Model\Configuration->__construct('dotpay')
#2 /www/modules/dotpay/sdk/Dotpay/Loader/Loader.php(217): ReflectionClass->newInstanceArgs(Array)
#3 /www/modules/dotpay/sdk/Dotpay/Loader/Loader.php(122): Dotpay\Loader\Loader->getObjectInstance(Object(Dotpay\Loader\Xml\Object), Array)
#4 /www/modules/dotpay/dotpay.php(105): Dotpay\Loader\Loader->get('Config')
#5 [internal function]: dotpay->__construct()
#6 /www/src/Core/Foundation/IoC/Container.php(125): ReflectionClass->newInstance()
#7 /www/src/Core/Foundat" while reading response header from upstream
```

**Comment by tbajorek** [comment]
Proszę sprawdzić, czy najnowsza wersja działa poprawnie:
[https://github.com/dotpay/PrestaShop-1.7.x/releases/tag/v1.0.2](https://github.com/dotpay/PrestaShop-1.7.x/releases/tag/v1.0.2)

**Comment by dudekk** [comment]
Ten błąd występuje właśnie w wersji 1.0.2 modułu, moduł się nie instaluje. Wersja 1.0.1 na czystej instalacji Prestashop instaluje się z błędem podczas instalacji, ale moduł później widnieje na liście i działa.

**Comment by tbajorek** [comment]
Wprowadziłem do tej wersji modyfikację, proszę pobrać plik z GH i spróbować, czy błąd został naprawiony.

**Comment by dudekk** [comment]
Po próbie instalacji modułu z master brancha ten sam problem:

"Server responded with 500 code."

a w logach http:

```
2017/04/27 15:19:14 [error] 3933#3933: *2841 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Dotpay\Exception\BadParameter\IdException in /www/modules/dotpay/sdk/Dotpay/Model/Configuration.php:695
Stack trace:
#0 /www/modules/dotpay/classes/Dotpay/Model/Configuration.php(108): Dotpay\Model\Configuration->setId(false)
#1 [internal function]: Prestashop\Dotpay\Model\Configuration->__construct('dotpay')
#2 /www/modules/dotpay/sdk/Dotpay/Loader/Loader.php(217): ReflectionClass->newInstanceArgs(Array)
#3 /www/modules/dotpay/sdk/Dotpay/Loader/Loader.php(122): Dotpay\Loader\Loader->getObjectInstance(Object(Dotpay\Loader\Xml\Object), Array)
#4 /www/modules/dotpay/dotpay.php(105): Dotpay\Loader\Loader->get('Config')
#5 [internal function]: dotpay->__construct()
#6 /www/src/Core/Foundation/IoC/Container.php(125): ReflectionClass->newInstance()
#7 /www/src/Core/Foundat" while reading response header from upstream, client: x, server: x, request: "POST /admin/index.php/module/import?_token=x HTTP/1.1", upstream: "fastcgi://unix:/run/php/x", host: "x", referrer: "https://x/admin/index.php/module/manage?_token=x"

```

**Comment by dudekk** [comment]
Wziąłem się za testowanie płatności i niestety po kliknięciu "Zamów z obowiązkiem zapłaty" otwiera się strona Dotpay:

> Wystąpił błąd
> Realizacja płatności chwilowo niemożliwa. Prosimy spróbować później.
> Prosimy kontaktować się bezpośrednio ze sprzedawcą

W logach w panelu Dotpay dla każdej nieudanej próby są podobne błędy:

```
27-04-2017 20:51:22	Warning	Błąd API płatności	Optional Chk obtained, but hash not equal. Obtained Chk "d1402944bb9ea800f1141c98185303ba991f2e91b4e5cba77883a03998122f25", but expected Chk "5e7652c358dabf5fe3933bbd82ea35e6b17eab8e2157293a2e7a737d389e0a0e"	
27-04-2017 20:48:20	Warning	Błąd API płatności	Optional Chk obtained, but hash not equal. Obtained Chk "e6196fd3915ab5c4d1df858f17d89c8f1ad6197ce5121dacfbc8f8a5c95d6ad3", but expected Chk "54c96484ca53eaf70b4a60ae1dd974e4c831f57298727436e2c723dccfeed630"	
27-04-2017 20:45:39	Warning	Błąd API płatności	Optional Chk obtained, but hash not equal. Obtained Chk "b1debf84df42d78675a84ba012e56a7569f704f4ba80d92005f4d2f93559a9e8", but expected Chk "98cacaaa339d3a69520f8252024c20dccdc92d5838180cd5e6a82621a117b35d"	
```

**Comment by wpawel** [comment]
Cytowany komunikat z logów w panelu Dotpay świadczy o tym, że parametr sumy kontrolnej CHK zawiera błędną wartość w stosunku do spodziewanej. Do wyliczenia sumy kontrolnej z przekazywanych parametrów potrzebny jest prawidłowo przepisany PIN z panelu konta Dotpay do konfiguracji modułu płatności. 
Proszę zatem wprowadzić prawidłowy PIN w konfiguracji modułu.

**Comment by dudekk** [comment]
Faktycznie, dziękuję, był błąd w PIN-ie :)
Czyli tak:
- moduł w wersji 1.0.1 generalnie działa, przetestowałem płatności i wszystko ok. Jest jedynie błąd podczas instalacji modułu: "Ups coś poszło nie tak. Moduł nie zwrócił żadnych szczegółowych informacji"
- moduł w wersji 1.0.2 nie działa, nie instaluje się (https://github.com/dotpay/PrestaShop-1.7.x/issues/1#issuecomment-297711339) i powoduje wykrzaczenie się panelu administracyjnego (Error 500) w sekcji Płatność -> Płatności. Żeby przywrócić panel do działania musiałem ręcznie usunąć katalog /modules/dotpay, na liście zainstalowanych modułów moduł się nie pojawiał.

**Comment by tbajorek** [comment]
Proszę sprawdzić wersję 1.0.3 spod tego adresu:
[https://github.com/dotpay/PrestaShop-1.7.x/releases/tag/v1.0.3](https://github.com/dotpay/PrestaShop-1.7.x/releases/tag/v1.0.3)
W obydwu powyższych wersjach występuje prawdopodobnie ten sam błąd, związany z inicjalizacją ustawień modułu, tyle że objawia się na różne sposoby.

**Comment by dudekk** [comment]
1.0.3 instaluje się z błędem "Ups, coś poszło nie tak", jednak pojawia się w zainstalowanych modułach i jest używalny

```
2017/05/03 19:34:39 [error] 3932#3932: *21962 FastCGI sent in stderr: "ice:  Undefined property: Context::$id_shop in /www/modules/dotpay/classes/Dotpay/Model/Configuration.php on line 475
PHP message: PHP Notice:  Undefined property: Context::$id_lang in /www/modules/dotpay/classes/Dotpay/Model/Configuration.php on line 475
PHP message: PHP Notice:  Undefined property: Context::$id_shop_group in /www/modules/dotpay/classes/Dotpay/Model/Configuration.php on line 475
PHP message: PHP Notice:  Undefined property: Context::$id_shop in /www/modules/dotpay/classes/Dotpay/Model/Configuration.php on line 475
PHP message: PHP Notice:  Undefined property: Context::$id_lang in /www/modules/dotpay/classes/Dotpay/Model/Configuration.php on line 475
PHP message: PHP Notice:  Undefined property: Context::$id_shop_group in /www/modules/dotpay/classes/Dotpay/Model/Configuration.php on line 475
PHP message: PHP Notice:  Undefined property: Context::$id_shop in /www/modules/dotpay/classes/Dotpay/Model/Configuration.php on line 475
PHP message: PHP Notice:  Undefined property: Context::$id_lang in /www/modules/dotpay/classes/Dotpay/Model/Configuration.php on line 475
PHP message: PHP Notice:  Undefined property: Context::$id_shop_group in /www/modules/dotpay/classes/Dotpay/Model/Configuration.php on line 475
PHP message: PHP Notice:  Undefined property: Context::$id_shop in /www/modules/dotpay/classes/Dotpay/Model/Configuration.php on line 475
PHP message: PHP Notice:  Undefined property: Context::$id_lang in /www/modules/dotpay/classes/Dotpay/Model/Configuration.php on line 475
PHP message: PHP Notice:  Undefined property: Context::$id_shop_group in /www/modules/dotpay/classes/Dotpay/Mode
```

**Comment by tbajorek** [comment]
Proszę sprawdzić najnowszą aktualizację wersji:
[https://github.com/dotpay/PrestaShop-1.7.x/releases/tag/v1.0.3](https://github.com/dotpay/PrestaShop-1.7.x/releases/tag/v1.0.3)
Mam nadzieję, że teraz zadziała. Jeżeliby jednakze nadal występował jakiś problem, proszę o podanie dokładnej wersji Pana instalacji Prestashop.

**Comment by dudekk** [comment]
Wrzuciłem wersję z mastera (tag 1.0.3 nie ma tych ostatnich poprawek) i nie ma już tych błędów PHP w logu serwera http, jednak Presta dalej w podsumowaniu wyrzuca, że "Ups coś poszło nie tak" :)
Wersja PrestaShop: 1.7.1.1
Jeśli chcesz mogę dać Ci dostęp do sklepu (jest jeszcze nieopublikowany więc można potestować), napisz na konrad [at] dudekk [dot] pl
